var qansPaper = [

    { "question": "page01", "ans": 3  },
    { "question": "page02", "ans": 4  },
    { "question": "page03", "ans": 3  },
    { "question": "page04", "ans": 1  },
    { "question": "page05", "ans": 1  },
    { "question": "page06", "ans": 2  },
    { "question": "page07", "ans": 2  },
    { "question": "page08", "ans": 1  },
    { "question": "page09", "ans": 2  },
    { "question": "page10", "ans": 1  },
    { "question": "page11", "ans": 2  },
    { "question": "page12", "ans": 1  },
    { "question": "page13", "ans": 1  },
    { "question": "page14", "ans": 1  },    
	{ "question": "page15", "ans": 3  },
    { "question": "page16", "ans": 2  },
    { "question": "page17", "ans": 2  },
    { "question": "page18", "ans": 1  },
    { "question": "page19", "ans": 2  },
    { "question": "page20", "ans": 1  },
    { "question": "page21", "ans": 1  },
    { "question": "page22", "ans": 3  },
    { "question": "page23", "ans": 4  },
    { "question": "page24", "ans": 2  },
    { "question": "page25", "ans": 1  },
    { "question": "page26", "ans": 4  },
    { "question": "page27", "ans": 2  },
    { "question": "page28", "ans": 3  },
    { "question": "page29", "ans": 1  },
    { "question": "page30", "ans": 1  },
    { "question": "page31", "ans": 4  },
    { "question": "page32", "ans": 2  },    
    { "question": "page33", "ans": 3  },
    { "question": "page34", "ans": 1  },
    { "question": "page35", "ans": 4  },    
    { "question": "page36", "ans": 3  },    
    { "question": "page37", "ans": 1  },
    { "question": "page38", "ans": 1  },
    { "question": "page39", "ans": 2  },
    { "question": "page40", "ans": 3  },
    { "question": "page41", "ans": 1  },
    { "question": "page42", "ans": 2  },
    { "question": "page43", "ans": 4  },
    { "question": "page44", "ans": 4  },
    { "question": "page45", "ans": 2  },
    { "question": "page46", "ans": 4  },
    { "question": "page47", "ans": 3  },
    { "question": "page48", "ans": 1  },
    { "question": "page49", "ans": 4  },
    { "question": "page50", "ans": 4  },  
    { "question": "page51", "ans": 4  },
    { "question": "page52", "ans": 1  },
   
    
     ];