var qansPaper = [

    { "question": "page01", "ans":  2 },
    { "question": "page02", "ans":  4 },
    { "question": "page03", "ans":  3 },
    { "question": "page04", "ans":  4 },
    { "question": "page05", "ans":  4 },
    { "question": "page06", "ans":  3 },
    { "question": "page07", "ans":  2 },
    { "question": "page08", "ans":  1 },
    { "question": "page09", "ans":  2 },
    { "question": "page10", "ans":  4 },
    { "question": "page11", "ans":  4 },
    { "question": "page12", "ans":  4 },
    { "question": "page13", "ans":  4 },
    { "question": "page14", "ans":  2 },    
	{ "question": "page15", "ans":  3 },
    { "question": "page16", "ans":  3 },
    { "question": "page17", "ans":  4 },
    { "question": "page18", "ans":  1 },
    { "question": "page19", "ans":  3 },
    { "question": "page20", "ans":  3 },
    { "question": "page21", "ans":  3 },
    { "question": "page22", "ans":  3 },
    { "question": "page23", "ans":  1 },
    { "question": "page24", "ans":  3 },
    { "question": "page25", "ans":  2 },
    { "question": "page26", "ans":  1 },
    { "question": "page27", "ans":  1 },
    { "question": "page28", "ans":  2 },
   
    
];