var qansPaper = [

    { "question": "page01", "ans":  2 },
    { "question": "page02", "ans":  1 },
    { "question": "page03", "ans":  3 },
    { "question": "page04", "ans":  2 },
    { "question": "page05", "ans":  4 },
    { "question": "page06", "ans":  3 },
    { "question": "page07", "ans":  3 },
    { "question": "page08", "ans":  4 },
    { "question": "page09", "ans":  3 },
    { "question": "page10", "ans":  3 },
    { "question": "page11", "ans":  1 },
    { "question": "page12", "ans":  2 },
    { "question": "page13", "ans":  2 },
    { "question": "page14", "ans":  1 },    
	{ "question": "page15", "ans":  4 },
    { "question": "page16", "ans":  1 },
    { "question": "page17", "ans":  2 },
    { "question": "page18", "ans":  2 },
    { "question": "page19", "ans":  4 },
    { "question": "page20", "ans":  1 },
    { "question": "page21", "ans":  2 },
    { "question": "page22", "ans":  1 },
    { "question": "page23", "ans":  2 },
    { "question": "page24", "ans":  2 },
    { "question": "page25", "ans":  4 },
    { "question": "page26", "ans":  4 },
    { "question": "page27", "ans":  4 },
    { "question": "page28", "ans":  1 },
    { "question": "page29", "ans":  3 },
    { "question": "page30", "ans":  2 },
    { "question": "page31", "ans":  4 },
    { "question": "page32", "ans":  1 },    
    { "question": "page33", "ans":  4 },
    { "question": "page34", "ans":  1 },
    { "question": "page35", "ans":  1 },    
    { "question": "page36", "ans":  2 },    
    { "question": "page37", "ans":  3 },
    { "question": "page38", "ans":  4 },
    { "question": "page39", "ans":  4 },
    { "question": "page40", "ans":  1 },
    { "question": "page41", "ans":  3 },
    { "question": "page42", "ans":  3 },
    { "question": "page43", "ans":  1 },
    { "question": "page44", "ans":  2 },
    { "question": "page45", "ans":  4 },
    
   
    
     ];