var qansPaper = [

    { "question": "page01", "ans": 3  },
    { "question": "page02", "ans": 4  },
    { "question": "page03", "ans": 1  },
    { "question": "page04", "ans": 3  },
    { "question": "page05", "ans": 2  },
    { "question": "page06", "ans": 2  },
    { "question": "page07", "ans": 2  },
    { "question": "page08", "ans": 3  },
    { "question": "page09", "ans": 3  },
    { "question": "page10", "ans": 4  },
    { "question": "page11", "ans": 3  },
    { "question": "page12", "ans": 2  },
    { "question": "page13", "ans": 3  },
    { "question": "page14", "ans": 3  },    
	{ "question": "page15", "ans": 3  },
    { "question": "page16", "ans": 1  },
    { "question": "page17", "ans": 3  },
    { "question": "page18", "ans": 4  },
    { "question": "page19", "ans": 4  },
    { "question": "page20", "ans": 1  },
    { "question": "page21", "ans": 3  },
    { "question": "page22", "ans": 1  },
    { "question": "page23", "ans": 2  },
    { "question": "page24", "ans": 4  },
    { "question": "page25", "ans": 4  },
    { "question": "page26", "ans": 1  },
    { "question": "page27", "ans": 3  },
    { "question": "page28", "ans": 3  },
    { "question": "page29", "ans": 4  },
    { "question": "page30", "ans": 4  },
    { "question": "page31", "ans": 4  },
    { "question": "page32", "ans": 2  },    
    { "question": "page33", "ans": 3  },
    
    
];