var qansPaper = [

    { "question": "page01", "ans": 2 },
    { "question": "page02", "ans": 1 },
    { "question": "page03", "ans": 2 },
    { "question": "page04", "ans": 1 },
    { "question": "page05", "ans": 4 },
    { "question": "page06", "ans": 1 },
    { "question": "page07", "ans": 1 },
    { "question": "page08", "ans": 2 },
    { "question": "page09", "ans": 2 },
    { "question": "page10", "ans": 3 },
    { "question": "page11", "ans": 4 },
    { "question": "page12", "ans": 2 },
    { "question": "page13", "ans": 3 },
    { "question": "page14", "ans": 4 },    
	{ "question": "page15", "ans": 3 },
    { "question": "page16", "ans": 2 },
    { "question": "page17", "ans": 1 },
    { "question": "page18", "ans": 2 },
    { "question": "page19", "ans": 2 },
    { "question": "page20", "ans": 4 },
    { "question": "page21", "ans": 1275 },
    { "question": "page22", "ans": 25 },
    { "question": "page23", "ans": 5},
    { "question": "page24", "ans": 3.00},
    { "question": "page25", "ans": 9.00},
    { "question": "page26", "ans": 31.00 },
    { "question": "page27", "ans": 11.00 },
    { "question": "page28", "ans": 19 },
    { "question": "page29", "ans": 2 },
    { "question": "page30", "ans": 14 },
    { "question": "page31", "ans": 1 },
    { "question": "page32", "ans": 1 },    
    { "question": "page33", "ans": 3 },
    { "question": "page34", "ans": 2 },
    { "question": "page35", "ans": 2 },    
    { "question": "page36", "ans": 4 },    
    { "question": "page37", "ans": 3 },
    { "question": "page38", "ans": 1 },
    { "question": "page39", "ans": 4 },
    { "question": "page40", "ans": 2 },
    { "question": "page41", "ans": 4 },
    { "question": "page42", "ans": 1 },
    { "question": "page43", "ans": 4 },
    { "question": "page44", "ans": 3 },
    { "question": "page45", "ans": 2 },
    { "question": "page46", "ans": 2 },
    { "question": "page47", "ans": 2 },
    { "question": "page48", "ans": 1 },
    { "question": "page49", "ans": 1 },
    { "question": "page50", "ans": 1 },  
    { "question": "page51", "ans": 1 },
    { "question": "page52", "ans": 10 },
    { "question": "page53", "ans": 18 },
    { "question": "page54", "ans": 9 },
    { "question": "page55", "ans": 900 },
    { "question": "page56", "ans": 18 },
    { "question": "page57", "ans": 2 },
    { "question": "page58", "ans": 125 },    
    { "question": "page59", "ans": 121 },
    { "question": "page60", "ans":25 },
    { "question": "page61", "ans": 2 },    
    { "question": "page62", "ans": 4 },    
    { "question": "page63", "ans": 4 },
    { "question": "page64", "ans": 3 },
    { "question": "page65", "ans": 4 },
    { "question": "page66", "ans": 2 },
    { "question": "page67", "ans": 4 },
    { "question": "page68", "ans": 1 },
    { "question": "page69", "ans": 4 },
    { "question": "page70", "ans": 2 },
    { "question": "page71", "ans": 3 },
    { "question": "page72", "ans": 3 },
    { "question": "page73", "ans": 2 },
    { "question": "page74", "ans": 2 },
    { "question": "page76", "ans": 3},
	{ "question": "page77", "ans": 3 },
    { "question": "page78", "ans": 3 },
    { "question": "page79", "ans": 1 },
    { "question": "page80", "ans": 3 },
    { "question": "page81", "ans": 02 },
    { "question": "page82", "ans": 1 }, 	
    { "question": "page83", "ans": 1200 },
	{ "question": "page84", "ans": 82 },
	{ "question": "page85", "ans": 11 },
	{ "question": "page86", "ans": 3 },
	{ "question": "page87", "ans": 11 },
	{ "question": "page88", "ans": 70 },
	{ "question": "page89", "ans": 3 },
	{ "question": "page90", "ans": 02 },
	
];