var qansPaper = [

    { "question": "page01", "ans":  1 },
    { "question": "page02", "ans":  2 },
    { "question": "page03", "ans":  2 },
    { "question": "page04", "ans":  1 },
    { "question": "page05", "ans":  3 },
    { "question": "page06", "ans":  1 },
    { "question": "page07", "ans":  2 },
    { "question": "page08", "ans":  2 },
    { "question": "page09", "ans":  1 },
    { "question": "page10", "ans":  4 },
    { "question": "page11", "ans":  2 },
    { "question": "page12", "ans":  1 },
    { "question": "page13", "ans":  2 },
    { "question": "page14", "ans":  1 },    
	{ "question": "page15", "ans":  1 },
    { "question": "page16", "ans":  81.6 },
    { "question": "page17", "ans":  3 },
    { "question": "page18", "ans":  .25 },
    { "question": "page19", "ans":  8 },
    { "question": "page20", "ans":  12.0 },
    { "question": "page21", "ans":  27 },
    { "question": "page22", "ans":  1 },
    { "question": "page23", "ans":  2 },
    { "question": "page24", "ans":  4 },
    { "question": "page25", "ans":  1 },
    { "question": "page26", "ans":  1 },
    { "question": "page27", "ans":  1 },
    { "question": "page28", "ans":  4 },
    { "question": "page29", "ans":  1 },
    { "question": "page30", "ans":  3 },
    { "question": "page31", "ans":  2 },
    { "question": "page32", "ans":  1 },    
    { "question": "page33", "ans":  1 },
    { "question": "page34", "ans":  1 },
    { "question": "page35", "ans":  1.0},    
    { "question": "page36", "ans":  6 },    
    { "question": "page37", "ans":  10.0},
    { "question": "page38", "ans":  1 },
    { "question": "page39", "ans":  2 },
    { "question": "page40", "ans":  16.0},
    { "question": "page41", "ans":  8 },
    { "question": "page42", "ans":  556},
    { "question": "page43", "ans":  2 },
    { "question": "page44", "ans":  1 },
    { "question": "page45", "ans":  1 },
    { "question": "page46", "ans":  1 },
    { "question": "page47", "ans":  1 },
    { "question": "page48", "ans":  4 },
    { "question": "page49", "ans":  2 },
    { "question": "page50", "ans":  1 },  
    { "question": "page51", "ans":  3 },
    { "question": "page52", "ans":  2 },
    { "question": "page53", "ans":  1 },
    { "question": "page54", "ans":  4 },
    { "question": "page55", "ans":  1 },
    { "question": "page56", "ans":  24 },
    { "question": "page57", "ans":  6 },
    { "question": "page58", "ans":  12 },
    { "question": "page59", "ans":  19 },
	
	];