var qansPaper = [

    { "question": "page01", "ans": 2 },
    { "question": "page02", "ans": 2 },
    { "question": "page03", "ans": 3 },
    { "question": "page04", "ans": 3 },
    { "question": "page05", "ans": 1 },
    { "question": "page06", "ans": 2 },
    { "question": "page07", "ans": 4 },
    { "question": "page08", "ans": 2 },
    { "question": "page09", "ans": 3 },
    { "question": "page10", "ans": 4 },
    { "question": "page11", "ans": 1 },
    { "question": "page12", "ans": 1 },
    { "question": "page13", "ans": 3 },
    { "question": "page14", "ans": 3 },    
	{ "question": "page15", "ans": 4 },
    { "question": "page16", "ans": 2 },
    { "question": "page17", "ans": 4 },
    { "question": "page18", "ans": 3 },
    { "question": "page19", "ans": 2 },
    { "question": "page20", "ans": 2 },
    { "question": "page21", "ans": 4898 },
    { "question": "page22", "ans": 16 },
    { "question": "page23", "ans": 151},
    { "question": "page24", "ans": 4.00},
    { "question": "page25", "ans": 960.0},
    { "question": "page26", "ans": 9525.0 },
    { "question": "page27", "ans": 32.0},
    { "question": "page28", "ans": 8 },
    { "question": "page29", "ans": 16 },
    { "question": "page30", "ans": 6 },
    { "question": "page31", "ans": 1 },
    { "question": "page32", "ans": 1 },    
    { "question": "page33", "ans": 2 },
    { "question": "page34", "ans": 2 },
    { "question": "page35", "ans": 3},    
    { "question": "page36", "ans": 1 },    
    { "question": "page37", "ans": 2 },
    { "question": "page38", "ans": 3 },
    { "question": "page39", "ans": 4 },
    { "question": "page40", "ans": 2 },
    { "question": "page41", "ans": 2 },
    { "question": "page42", "ans": 1 },
    { "question": "page43", "ans": 1 },
    { "question": "page44", "ans": 1 },
    { "question": "page45", "ans": 2 },
    { "question": "page46", "ans": 1 },
    { "question": "page47", "ans": 1 },
    { "question": "page48", "ans": 1 },
    { "question": "page49", "ans": 4 },
    { "question": "page50", "ans": 2 },  
    { "question": "page51", "ans": 20 },
    { "question": "page52", "ans": 15 },
    { "question": "page53", "ans": 16 },
    { "question": "page54", "ans": 30 },
    { "question": "page55", "ans": 100 },
    { "question": "page56", "ans": 6 },
    { "question": "page57", "ans": 2 },
    { "question": "page58", "ans": 18 },    
    { "question": "page59", "ans": 245 },
    { "question": "page60", "ans": 20 },
    { "question": "page61", "ans": 2 },    
    { "question": "page62", "ans": 3 },    
    { "question": "page63", "ans": 3 },
    { "question": "page64", "ans": 1 },
    { "question": "page65", "ans": 3 },
    { "question": "page66", "ans": 4 },
    { "question": "page67", "ans": 4 },
    { "question": "page68", "ans": 1 },
    { "question": "page69", "ans": 2 },
    { "question": "page70", "ans": 3 },
    { "question": "page71", "ans": 1 },
    { "question": "page72", "ans": 4 },
    { "question": "page73", "ans": 1 },
    { "question": "page74", "ans": 3 },
    { "question": "page75", "ans": 4},
	{ "question": "page76", "ans": 1 },
    { "question": "page77", "ans": 4 },
    { "question": "page78", "ans": 2 },
    { "question": "page79", "ans": 4 },
    { "question": "page80", "ans": 2 },
    { "question": "page81", "ans": 1825 }, 	
    { "question": "page82", "ans": 3 },
	{ "question": "page83", "ans": 2 },
	{ "question": "page84", "ans": 3 },
	{ "question": "page85", "ans": 3 },
	{ "question": "page86", "ans": 5 },
	{ "question": "page87", "ans": 30 },
	{ "question": "page88", "ans": 0 },
	{ "question": "page89", "ans": 1567 },
    { "question": "page90", "ans": 1 },
	
];