var qansPaper=[

    {"question":"page01", "ans":  1},
    {"question":"page02", "ans":  1},
    {"question":"page03", "ans":  4},
    {"question":"page04", "ans":  3},
    {"question":"page05", "ans":  3},
    {"question":"page06", "ans":  1},
    {"question":"page07", "ans":  3},
    {"question":"page08", "ans":  3},
    {"question":"page09", "ans":  4},
    {"question":"page10", "ans":  1},
    {"question":"page11", "ans":  2},
    {"question":"page12", "ans":  1},
    {"question":"page13", "ans":  4},
    {"question":"page14", "ans":  1},    
	{"question":"page15", "ans":  3},
    {"question":"page16", "ans":  2},
    {"question":"page17", "ans":  3},
    {"question":"page18", "ans":  1},
    {"question":"page19", "ans":  4},
    {"question":"page20", "ans":  3},
    {"question":"page21", "ans":  4},
    {"question":"page22", "ans":  3},
    {"question":"page23", "ans":  3},
    {"question":"page24", "ans":  2},
    {"question":"page25", "ans":  3},
];