var qansPaper = [

    { "question": "page01", "ans":  2 },
    { "question": "page02", "ans":  9 },
    { "question": "page03", "ans":  6 },
    { "question": "page04", "ans":  4 },
    { "question": "page05", "ans":  2 },
    { "question": "page06", "ans":  6 },
    { "question": "page07", "ans":  14 },
    { "question": "page08", "ans":  14 },
    { "question": "page09", "ans":  134 },
    { "question": "page10", "ans":  13 },
    { "question": "page11", "ans":  13 },
    { "question": "page12", "ans":  1234 },
    { "question": "page13", "ans":  2.05 },
    { "question": "page14", "ans":  .26 },    
	{ "question": "page15", "ans":  1.30 },
    { "question": "page16", "ans":   .24 },
    { "question": "page17", "ans":  55.0 },
    { "question": "page18", "ans":  8.33 },
    { "question": "page19", "ans":  9 },
    { "question": "page20", "ans":  6 },
    { "question": "page21", "ans":  6 },
    { "question": "page22", "ans":  4 },
    { "question": "page23", "ans":  5 },
    { "question": "page24", "ans":  6 },
    { "question": "page25", "ans":  123 },
    { "question": "page26", "ans":  1 },
    { "question": "page27", "ans":  1234 },
    { "question": "page28", "ans":   123 },
    { "question": "page29", "ans":  34 },
    { "question": "page30", "ans":  23 },
    { "question": "page31", "ans":  2.3},
    { "question": "page32", "ans":  .20 },    
    { "question": "page33", "ans":  -2640.0 },
    { "question": "page34", "ans":  18.60 },
    { "question": "page35", "ans":  935.00 },    
    { "question": "page36", "ans":  .20 },    
    { "question": "page37", "ans":  8 },
    { "question": "page38", "ans":  6 },
    { "question": "page39", "ans":  2 },
    { "question": "page40", "ans":  5 },
    { "question": "page41", "ans":  4 },
    { "question": "page42", "ans":  8 },
    { "question": "page43", "ans":  13 },
    { "question": "page44", "ans":  14 },
    { "question": "page45", "ans":  124 },
    { "question": "page46", "ans":  123 },
    { "question": "page47", "ans":  13 },
    { "question": "page48", "ans":  124 },
    { "question": "page49", "ans":  495.0 },
    { "question": "page50", "ans":  1080.0 },  
    { "question": "page51", "ans":  8.0},
    { "question": "page52", "ans":  19.0 },
    { "question": "page53", "ans":  4.0 },
    { "question": "page54", "ans":  0.5},
	
	];
