var qansPaper = [

    { "question": "page01", "ans":  2 },
    { "question": "page02", "ans":  123 },
    { "question": "page03", "ans":  34 },
    { "question": "page04", "ans":  134 },
    { "question": "page05", "ans":  12 },
    { "question": "page06", "ans":  234 },
    { "question": "page07", "ans":  3 },
    { "question": "page08", "ans":  2 },
    { "question": "page09", "ans":  5 },
    { "question": "page10", "ans":  4 },
    { "question": "page11", "ans":  4 },
    { "question": "page12", "ans":  3 },
    { "question": "page13", "ans":  6 },
    { "question": "page14", "ans":  3 },
	{ "question": "page15", "ans":  2 },
    { "question": "page16", "ans":  1 },
    { "question": "page17", "ans":  3 },
    { "question": "page18", "ans":  3 },
    { "question": "page19", "ans":  23 },
    { "question": "page20", "ans":  234 },
    { "question": "page21", "ans":  23},
    { "question": "page22", "ans":  123},
    { "question": "page23", "ans":  13 },
    { "question": "page24", "ans":  23 },
    { "question": "page25", "ans":  6 },
    { "question": "page26", "ans":  5 },
    { "question": "page27", "ans":  7 },
    { "question": "page28", "ans":  4 },
    { "question": "page29", "ans":  6 },
    { "question": "page30", "ans":  2 },
    { "question": "page31", "ans":  0 },
    { "question": "page32", "ans":  2 },    
    { "question": "page33", "ans":  2 },
    { "question": "page34", "ans":  3 },
    { "question": "page35", "ans":  3 },    
    { "question": "page36", "ans":  3 },    
    { "question": "page37", "ans":  12 },
    { "question": "page38", "ans":  123 },
    { "question": "page39", "ans":  1 },
    { "question": "page40", "ans":  34 },
    { "question": "page41", "ans":  234 },
    { "question": "page42", "ans":  3 },
    { "question": "page43", "ans":  1 },
    { "question": "page44", "ans":  8 },
    { "question": "page45", "ans":  5 },
    { "question": "page46", "ans":  1 },
    { "question": "page47", "ans":  5 },
    { "question": "page48", "ans":  3 },
    { "question": "page49", "ans":  7 },
    { "question": "page50", "ans":  6 },  
    { "question": "page51", "ans":  1 },
    { "question": "page52", "ans":  1 },
    { "question": "page53", "ans":  3 },
    { "question": "page54", "ans":  2 },
	
	];