var qansPaper = [

    { "question": "page01", "ans":  23 },
    { "question": "page02", "ans":  234 },
    { "question": "page03", "ans":  12 },
    { "question": "page04", "ans":  23 },
    { "question": "page05", "ans":  134 },
    { "question": "page06", "ans":  123 },
    { "question": "page07", "ans":  25.6 },
    { "question": "page08", "ans":  3.74 },
    { "question": "page09", "ans":  3.14 },
    { "question": "page10", "ans":  1.77 },
    { "question": "page11", "ans":  0.62 },
    { "question": "page12", "ans":  6.4 },
    { "question": "page13", "ans":  0 },
    { "question": "page14", "ans":  0 },    
	{ "question": "page15", "ans":  1 },
    { "question": "page16", "ans":  2 },
    { "question": "page17", "ans":  2 },
    { "question": "page18", "ans":  2 },
    { "question": "page19", "ans":  123 },
    { "question": "page20", "ans":  123 },
    { "question": "page21", "ans":  24 },
    { "question": "page22", "ans":  13 },
    { "question": "page23", "ans":  124 },
    { "question": "page24", "ans":  13 },
    { "question": "page25", "ans":  0.11 },
    { "question": "page26", "ans":  0.25 },
    { "question": "page27", "ans":  13.32 },
    { "question": "page28", "ans":  6.15 },
    { "question": "page29", "ans":  1.2 },
    { "question": "page30", "ans":  18 },
    { "question": "page31", "ans":  0 },
    { "question": "page32", "ans":  0 },    
    { "question": "page33", "ans":  2},
    { "question": "page34", "ans":  2 },
    { "question": "page35", "ans":  1},    
    { "question": "page36", "ans":  3 },    
    { "question": "page37", "ans":  13 },
    { "question": "page38", "ans":  234 },
    { "question": "page39", "ans":  23 },
    { "question": "page40", "ans":  23 },
    { "question": "page41", "ans":  12 },
    { "question": "page42", "ans":  124 },
    { "question": "page43", "ans":  8 },
    { "question": "page44", "ans":  1 },
    { "question": "page45", "ans":  1 },
    { "question": "page46", "ans":  108 },
    { "question": "page47", "ans":  5 },
    { "question": "page48", "ans":  1 },
    { "question": "page49", "ans":  0 },
    { "question": "page50", "ans":  0 },  
    { "question": "page51", "ans":  4 },
    { "question": "page52", "ans":  3},
    { "question": "page53", "ans":  1},
    { "question": "page54", "ans":  1 },
	
	];